export const enum NODETYPE {
    PROGRAM  = 'Program',
    BLOCK_STATEMENT = 'BlockStatement',
    CLASS_BODY = 'ClassBody',
    CLASS_DECLARATION = 'ClassDeclaration',
    EXPORT_DEFAULT_DECLARATION = 'ExportDefaultDeclaration',
    EXPORT_NAMED_DECLARATION = 'ExportNamedDeclaration',
    EXPORT_ALL_DECLARATION = 'ExportAllDeclaration',
    EXPORT_SPECIFIER = 'ExportSpecifier',
    FUNCTION_DECLARATION = 'FunctionDeclaration',
    FUNCTION_EXPRESSION = 'FunctionExpression',
    IMPORT_DECLARATION = 'ImportDeclaration',
    IMPORT_SPECIFIER = 'ImportSpecifier',
    IMPORT_DEFAULT_SPECIFIER = 'ImportDefaultSpecifier',
    IMPORT_NAMESPACE_SPECIFIER = 'ImportNamespaceSpecifier',
    IDENTIFIER = 'Identifier',
    LITERAL = 'Literal',
    METHOD_DEFINITION = 'MethodDefinition',
    VARIABLE_DECLARATION = 'VariableDeclaration',
    VARIABLE_DECLARATOR = 'VariableDeclarator',
}